name:  secrets ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  secrets-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Skripte ausführbar machen
        run: chmod +x scripts/*.sh



      - name: variablen skript ausführen
        run: bash scripts/03_secret_demo.sh
        env: 
          DEMO_API_TOKEN: ${{secrets.DEMO_API_TOKEN}}
      - name: read secret
        run:  echo $DEMO_API_TOKEN      
      - name: Report hochladen
        uses: actions/upload-artifact@v4
        with:
          name: secrets-report
          path: output/secret-report.txt

